# Generated by Django 5.0.1 on 2024-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thisapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1996-01-27"),
            preserve_default=False,
        ),
    ]
